module

public import Complexity.CookLevin
public import Complexity.SATBounds
import Lean.Elab.Tactic.Omega

/-!
Bit-length bounds for the explicit tableau-to-CNF encoding. All variable indices
and list lengths are charged according to the unary binary-word serialization.
These estimates concern output size; machine runtime is a separate obligation.
-/

@[expose] public section

namespace Complexity.CookLevinBounds

open CSPSAT LocalConstraint FiniteRows SATBounds

/-- General encoded-CNF bound, with variable identifiers bounded by `n`. -/
theorem encode_length_le (n : Nat) (f : SAT.CNF) (hf : ThreeSAT.CNFBelow n f) :
    (SAT.encode f).length ≤ (n + 2) * Constraints.literalCount f + 2 * f.length + 1 := by
  induction f with
  | nil => simp [Constraints.literalCount]
  | cons c f ih =>
    have hc := encodeClause_length_le n c (hf c List.mem_cons_self)
    have ht := ih (fun d hd => hf d (List.mem_cons_of_mem c hd))
    rw [encode_cons_length]
    simp only [Constraints.literalCount, List.length_cons, Nat.mul_add, Nat.mul_one]
    omega

/-- Every tuple generated by a bounded-depth decision tree has bounded arity. -/
theorem tuple_length_le_of_queries {m d : Nat} (n : Nat) (tree : Tree m d)
    (h : QueriesAtMost n tree) (target : Fin m) :
    ∀ tuple ∈ tree.encode target, tuple.length ≤ n + 1 := by
  induction n generalizing tree with
  | zero =>
    cases tree with
    | value val =>
      intro tuple ht
      obtain ⟨other, _, rfl⟩ := List.mem_map.mp ht
      simp
    | query slot branches => exact False.elim h
  | succ n ih =>
    cases tree with
    | value val =>
      intro tuple ht
      obtain ⟨other, _, rfl⟩ := List.mem_map.mp ht
      simp
    | query slot branches =>
      intro tuple ht
      obtain ⟨value, _, hv⟩ := List.mem_flatMap.mp ht
      obtain ⟨rest, hr, rfl⟩ := List.mem_map.mp hv
      have hl := ih _ (h value) rest hr
      simpa only [List.length_cons] using Nat.succ_le_succ hl

theorem mapVars_queries {m n d : Nat} (tree : Tree m d) (f : Fin m → Fin n)
    (k : Nat) (h : QueriesAtMost k tree) : QueriesAtMost k (tree.mapVars f) := by
  induction k generalizing tree with
  | zero => cases tree <;> exact h
  | succ k ih =>
    cases tree with
    | value val => trivial
    | query slot branches => exact fun value => ih _ (h value)

theorem instanceSize_le_of_arity {m d : Nat} (I : Instance m d) (arity : Nat)
    (h : ∀ tuple ∈ I, tuple.length ≤ arity) : instanceSize I ≤ arity * I.length := by
  induction I with
  | nil => simp [instanceSize]
  | cons tuple rest ih =>
    have hh := h tuple List.mem_cons_self
    have ht := ih (fun t ht => h t (List.mem_cons_of_mem tuple ht))
    simp only [instanceSize, List.length_cons, Nat.mul_add, Nat.mul_one]
    omega

theorem csp_encode_bit_length_le {m d : Nat} (I : Instance m d) (arity : Nat)
    (h : ∀ tuple ∈ I, tuple.length ≤ arity) :
    (SAT.encode (CSPSAT.encode I)).length ≤
      (m * (d + 1) + 2) * (m * ((d + 1) + 2 * ((d + 1) * (d + 1))) + arity * I.length) +
      2 * (m * ((d + 1) * (d + 1) + 1) + I.length) + 1 := by
  have hbit := encode_length_le (m * (d + 1)) (CSPSAT.encode I)
    (fun _ hc _ hl => encode_variables_lt I hc hl)
  have hlit := encode_literalCount_le I
  have har := instanceSize_le_of_arity I arity h
  have hcl := CSPSAT.encode_length_le I
  have hmul := Nat.mul_le_mul_left (m * (d + 1) + 2)
    (Nat.le_trans hlit (Nat.add_le_add_left har _))
  have hmul2 := Nat.mul_le_mul_left 2 hcl
  omega


theorem pin_length_le {m d : Nat} (slot : Fin m) (value : Fin (d + 1)) :
    (InitialWord.pin slot value).length ≤ d + 1 := by
  simpa [InitialWord.pin, Tree.leaves] using
    LocalConstraint.encode_length_le (Tree.value value) slot

theorem pin_arity {m d : Nat} (slot : Fin m) (value : Fin (d + 1)) :
    ∀ tuple ∈ InitialWord.pin slot value, tuple.length ≤ 1 :=
  tuple_length_le_of_queries 0 (Tree.value value) trivial slot

theorem allow_length_le {m d : Nat} (slot : Fin m) (values : List (Fin (d + 1))) :
    (InitialWord.allow slot values).length ≤ d + 1 := by
  simpa [InitialWord.allow] using
    List.length_filter_le (fun v => !values.contains v) (List.finRange (d + 1))

theorem allow_arity {m d : Nat} (slot : Fin m) (values : List (Fin (d + 1))) :
    ∀ tuple ∈ InitialWord.allow slot values, tuple.length ≤ 1 := by
  intro tuple ht
  obtain ⟨v, _, rfl⟩ := List.mem_map.mp ht
  simp

theorem rightCell_length_le (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (i : Fin width) : (InitialWord.rightCell M width pfx bound i).length ≤ M.states + 4 := by
  unfold InitialWord.rightCell
  split
  · exact pin_length_le _ _
  · split
    · exact allow_length_le _ _
    · exact pin_length_le _ _

theorem rightCell_arity (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (i : Fin width) :
    ∀ tuple ∈ InitialWord.rightCell M width pfx bound i, tuple.length ≤ 1 := by
  unfold InitialWord.rightCell
  split
  · exact pin_arity _ _
  · split
    · exact allow_arity _ _
    · exact pin_arity _ _

theorem blankCell_length_le (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (fit : pfx.length + bound ≤ width) (i : Fin width) :
    (InitialWord.blankCell M width pfx bound fit i).length ≤ M.states + 4 := by
  unfold InitialWord.blankCell
  split
  · rw [guard_length]
    exact pin_length_le _ _
  · simp

theorem blankCell_arity (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (fit : pfx.length + bound ≤ width) (i : Fin width) :
    ∀ tuple ∈ InitialWord.blankCell M width pfx bound fit i, tuple.length ≤ 2 := by
  unfold InitialWord.blankCell
  split
  · intro tuple ht
    obtain ⟨rest, hr, rfl⟩ := List.mem_map.mp ht
    have hh := pin_arity _ _ rest hr
    simp only [List.length_cons]
    omega
  · simp

theorem initial_length_le (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (fit : pfx.length + bound ≤ width) :
    (InitialWord.problem M width pfx bound fit).length ≤ (3 * width + 1) * (M.states + 4) := by
  have hs := pin_length_le (stateSlot width) (stateValue M M.start)
  have hl := flatMap_length_le (List.finRange width)
    (fun i => InitialWord.pin (leftSlot width i) (symbolValue M .blank)) (M.states + 4)
    (fun _ _ => pin_length_le _ _)
  have hr := flatMap_length_le (List.finRange width)
    (InitialWord.rightCell M width pfx bound) (M.states + 4)
    (fun i _ => rightCell_length_le M width pfx bound i)
  have hb := flatMap_length_le (List.finRange width)
    (InitialWord.blankCell M width pfx bound fit) (M.states + 4)
    (fun i _ => blankCell_length_le M width pfx bound fit i)
  simp only [List.length_finRange] at hl hr hb
  simp only [InitialWord.problem, List.length_append, Nat.add_mul, Nat.one_mul,
    Nat.mul_assoc]
  omega

theorem initial_arity (M : Machine) (width : Nat) (pfx : Word) (bound : Nat)
    (fit : pfx.length + bound ≤ width) :
    ∀ tuple ∈ InitialWord.problem M width pfx bound fit, tuple.length ≤ 4 := by
  intro tuple ht
  simp only [InitialWord.problem, List.mem_append] at ht
  rcases ht with ((ht | ht) | ht) | ht
  · have := pin_arity _ _ tuple ht; omega
  · obtain ⟨i, _, hi⟩ := List.mem_flatMap.mp ht
    have := pin_arity _ _ tuple hi; omega
  · obtain ⟨i, _, hi⟩ := List.mem_flatMap.mp ht
    have := rightCell_arity M width pfx bound i tuple hi; omega
  · obtain ⟨i, _, hi⟩ := List.mem_flatMap.mp ht
    have := blankCell_arity M width pfx bound fit i tuple hi; omega

theorem mapInstance_arity {m n d arity : Nat} (f : Fin m → Fin n) (I : Instance m d)
    (h : ∀ tuple ∈ I, tuple.length ≤ arity) :
    ∀ tuple ∈ Tableau.mapInstance f I, tuple.length ≤ arity := by
  intro tuple ht
  obtain ⟨rest, hr, rfl⟩ := List.mem_map.mp ht
  simpa [Tableau.mapTuple] using h rest hr

theorem tableau_arity (M : Machine) (width steps : Nat) (hwidth : 0 < width)
    (pfx : Word) (bound : Nat) (fit : pfx.length + bound ≤ width) :
    ∀ tuple ∈ Tableau.problem (CookLevin.transitionSystem M width hwidth) steps
      (InitialWord.problem M width pfx bound fit) (CookLevin.accepting M width),
      tuple.length ≤ 4 := by
  intro tuple ht
  simp only [Tableau.problem, List.mem_append] at ht
  rcases ht with hi | ht | hf
  · exact mapInstance_arity _ _ (initial_arity M width pfx bound fit) tuple hi
  · obtain ⟨time, _, ht⟩ := List.mem_flatMap.mp ht
    obtain ⟨position, _, hp⟩ := List.mem_flatMap.mp ht
    exact tuple_length_le_of_queries 3 _
      (mapVars_queries _ _ 3 (transitionTree_queries M width hwidth position)) _ tuple hp
  · apply mapInstance_arity _ _ (fun t ht => ?_) tuple hf
    have hh := pin_arity _ _ t ht
    omega

def tupleBound (M : Machine) (width steps : Nat) : Nat :=
  (3 * width + 2) * (M.states + 4) +
    steps * ((M.states + 4) * ((2 * width + 1) * (M.states + 4) ^ 3))

theorem tableau_length_le (M : Machine) (width steps : Nat) (hwidth : 0 < width)
    (pfx : Word) (bound : Nat) (fit : pfx.length + bound ≤ width) :
    (Tableau.problem (CookLevin.transitionSystem M width hwidth) steps
      (InitialWord.problem M width pfx bound fit) (CookLevin.accepting M width)).length ≤
      tupleBound M width steps := by
  have ht := Tableau.problem_length_le (CookLevin.transitionSystem M width hwidth) steps
    (InitialWord.problem M width pfx bound fit) (CookLevin.accepting M width)
  have hi := initial_length_le M width pfx bound fit
  have hf := pin_length_le (stateSlot width) (decisionValue M true)
  have hsys := CookLevin.transitionSystem_leaves_le M width hwidth
  have hmul := Nat.mul_le_mul_left steps (Nat.mul_le_mul_left (M.states + 4) hsys)
  change (CookLevin.accepting M width).length ≤ M.states + 4 at hf
  calc
    _ ≤ (3 * width + 1) * (M.states + 4) +
        steps * ((M.states + 4) * ((2 * width + 1) * (M.states + 4) ^ 3)) +
        (M.states + 4) := Nat.le_trans ht (Nat.add_le_add (Nat.add_le_add hi hmul) hf)
    _ = tupleBound M width steps := by
      simp only [tupleBound, Nat.add_mul, Nat.one_mul]
      omega

def bitBound (M : Machine) (width steps : Nat) : Nat :=
  let cells := (steps + 1) * (2 * width + 1)
  let domain := M.states + 4
  (cells * domain + 2) *
      (cells * (domain + 2 * (domain * domain)) + 4 * tupleBound M width steps) +
    2 * (cells * (domain * domain + 1) + tupleBound M width steps) + 1

/-- Explicit polynomial bit bound in the tableau width and time horizon. -/
theorem formula_bit_length_le (M : Machine) (width steps : Nat) (hwidth : 0 < width)
    (pfx : Word) (bound : Nat) (fit : pfx.length + bound ≤ width) :
    (SAT.encode (CookLevin.formula M width steps hwidth pfx bound fit)).length ≤
      bitBound M width steps := by
  have hc := csp_encode_bit_length_le _ 4 (tableau_arity M width steps hwidth pfx bound fit)
  have ht := tableau_length_le M width steps hwidth pfx bound fit
  have hmul := Nat.mul_le_mul_left (((steps + 1) * (2 * width + 1)) * (M.states + 4) + 2)
    (Nat.add_le_add_left (Nat.mul_le_mul_left 4 ht)
      (((steps + 1) * (2 * width + 1)) * ((M.states + 4) + 2 * ((M.states + 4) * (M.states + 4)))))
  have hmul2 := Nat.mul_le_mul_left 2
    (Nat.add_le_add_left ht (((steps + 1) * (2 * width + 1)) * ((M.states + 4) * (M.states + 4) + 1)))
  change (SAT.encode (CookLevin.formula M width steps hwidth pfx bound fit)).length ≤ _ at hc
  exact Nat.le_trans hc (Nat.add_le_add_right (Nat.add_le_add hmul hmul2) 1)

end Complexity.CookLevinBounds
